image: node:22 # ou une version Node.js adaptée à votre projet

stages:
  - build

variables:
  NODE_ENV: production

before_script:
  - apt-get update && apt-get install -y dpkg-dev fakeroot zip
  - npm install --include=dev

build_application:
  stage: build
  script:
    - npm run make
    - rm -r out/infodex-infinity-linux-x64
  artifacts:
    paths:
      - out/